const SET_BALANCE = "SET_BALANCE";
const DELETE_ACCOUNT = "DELETE_ACCOUNT";
const CREATE_ACCOUNT = "CREATE_ACCOUNT";
const EDIT_ACCOUNT = "EDIT_ACCOUNT";

export default { SET_BALANCE, DELETE_ACCOUNT, CREATE_ACCOUNT, EDIT_ACCOUNT }
