export const CREATE_NEW_TRANSACTION = "CREATE_NEW_TRANSACTION";
export const GET_TRANSACTION = "GET_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
