export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const GET_USER_DATA = "GET_USER_DATA";
export const DELETE_USER_DATA = "DELETE_USER_DATA";
export const SET_USER_TIME_ON_APP = "SET_USER_TIME_ON_APP";
