name: Android [Staging]

on:
  workflow_dispatch:
    inputs:
      force_release:
        description: Force re-publish release
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Set metro cache tmpdir
        run: |-
          echo $TMPDIR
          echo "METRO_CACHE=$TMPDIR/metro-cache" >> $GITHUB_ENV
      - name: Cache Metro Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.METRO_CACHE }}
          key: metro-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Setup env file
        run: cp .env.example .env.homolog

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - run: ./gradlew assembleHomologRelease -Dorg.gradle.logging.level=info --no-daemon
        working-directory: android
        name: Build Android apk (debug)

      - uses: actions/upload-artifact@v2
        with:
          name: app-homolog-release.apk
          path: android/app/build/outputs/apk/homolog/release/
